import { createApp } from 'vue'
// import App from './a-bind.vue'
// import App from './b-on-1.vue'
// import App from './b-on-2.vue'
// import App from './b-on-3.vue'
// import App from './b-on-4.vue'
// import App from './c-model-1.vue'
// import App from './c-model-2.vue'
// import App from './c-model-3.vue'
import App from './c-model-4.vue'
// import App from './d-文本内容.vue'
// import App from './e-条件渲染-1.vue'
// import App from './e-条件渲染-2.vue'
// import App from './f-循环渲染-1.vue'
// import App from './f-循环渲染-2.vue'
// import App from './f-循环渲染-3.vue'
// import App from './f-循环渲染-4.vue'
// import App from './g-dom树-1.vue'
// import App from './g-dom树-2.vue'

createApp(App).mount('#app')
